In [1]:
import torch

In [2]:
scores = torch.randint(0, 10, (4, 6))
scores

tensor([[6, 6, 5, 8, 4, 7],
        [3, 9, 5, 2, 0, 0],
        [2, 2, 6, 7, 3, 9],
        [4, 7, 9, 2, 8, 5]])

In [7]:
scale_scores = scores/scores.sum(dim=1,keepdim=True)

In [14]:
scale_scores

tensor([[0.1667, 0.1667, 0.1389, 0.2222, 0.1111, 0.1944],
        [0.1579, 0.4737, 0.2632, 0.1053, 0.0000, 0.0000],
        [0.0690, 0.0690, 0.2069, 0.2414, 0.1034, 0.3103],
        [0.1143, 0.2000, 0.2571, 0.0571, 0.2286, 0.1429]])

In [13]:
(scale_scores.sum(dim=0)/4)

tensor([0.1270, 0.2273, 0.2165, 0.1565, 0.1108, 0.1619])